# Generated by Django 4.0.3 on 2024-06-11 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoxData',
            fields=[
                ('sku_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('net_weight', models.FloatField()),
                ('length', models.IntegerField()),
                ('breadth', models.IntegerField()),
                ('height', models.IntegerField()),
            ],
            options={
                'db_table': 'box_data',
            },
        ),
        migrations.CreateModel(
            name='TruckData',
            fields=[
                ('number', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('type_id', models.CharField(max_length=255)),
                ('length', models.IntegerField()),
                ('breadth', models.IntegerField()),
                ('height', models.IntegerField()),
            ],
            options={
                'db_table': 'truck_data',
            },
        ),
    ]
