# Generated by Django 4.0.3 on 2024-06-11 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0003_delete_authgroup_delete_authgrouppermissions_and_more'),
    ]

    operations = [
    ]
